### PR TITLE
updating to include deploy resource scenario, initially the values ar…

### PR DESCRIPTION
**Pull request by toddrob**
…e hard-coded in the actiondialog.cs

Apologies guys for the last pull request.  Have a look at this one.

@dtzar 
@nzthiago

### CODE REVIEW

**Comment by dtzar** [comment]
LGTM as a step until we wire up LUIS & parameters input from Bot Form flow.  @nzthiago ?

**Comment by nzthiago** [comment]
I like to have this as reference for when we wire up LUIS - @dtzar do you think it should be in its own branch given the values are hardcoded?

**Comment by nzthiago** [comment]
Or leave in beta branch with hardcodes and update later / move the settings to web.config?

**Comment by dtzar** [comment]
No one can access this code via the Bot until we wire up LUIS, right?  If so - I'd say it's ok to merge to Beta branch.  That said my gut is - it would be good to get the docs changes cleanly pushed through to beta & master prior.  Also really depends on if you want a knowing non-functional piece of code in the Bot in general.  I'm open either way.

**Comment by dtzar** [comment]
We could also have him change the LUIS intent to something like "changeme" for now in case we wanted to restructure LUIS all together (including Create intent) so that way even if this code was in production no one could truly use it.

**Comment by dtzar** [comment]
We would change the hard-coded values of course to be form flow inputs as soon as we lit up the code to be accessed by the bot.

**Comment by toddrob** [comment]
That’s fine with me.  Do you want me to make this change and do another pull request?

**Pull request merged**
